# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202204

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [ ]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')  # 四捨五入到第二位
# print(np.round( A@C   ,2)), print(' ') # dimension error
# print(np.round( B@C   ,2)), print(' ') # dimension error
print(np.round( C.T@A ,2))

# Using pytorch

In [2]:
A  = torch.randn(3,4)
A

tensor([[-1.9483,  1.3808,  0.4766,  1.5188],
        [-0.0842, -0.8007, -1.3085, -0.8014],
        [-1.2204, -0.5017, -0.3412, -2.1603]])

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 0.1900,  2.0200,  0.6400,  1.0300,  0.2600, -0.6300, -2.9100],
        [-2.8500, -3.1700,  0.5400,  0.7600,  0.1000,  2.0400, -0.3300],
        [ 1.1000,  1.5200,  0.7100,  0.2400, -1.3600, -0.3700, -3.6000]],
       dtype=torch.float64)
 
tensor([[ 0.1900,  2.0200,  0.6400,  1.0300,  0.2600, -0.6300, -2.9100],
        [-2.8500, -3.1700,  0.5400,  0.7600,  0.1000,  2.0400, -0.3300],
        [ 1.1000,  1.5200,  0.7100,  0.2400, -1.3600, -0.3700, -3.6000]])
